name: Release Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      # - name: Get Build Info
      #   id: info
      #   shell: bash
      #   run: |
      #     d=`date +%Y%m%d`
      #     echo ::set-output name=DATE::${d:2:6}
      #     echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}

      - name: Set up Node.js Enviroment
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          SSSEC: ${{ secrets.SSSEC }}
        run: |
          yarn
          yarn run docs:build
          Set-Location docs/.vitepress/dist
          git init
          git config user.email "ihex@foxmail.com"
          git config user.name "Miswanting"
          git add -A
          git commit -m 'deploy'
          Write-Output "$env:SSSEC" > ../kkk
          New-Variable -Name Key -Value "../kkk"
          Icacls $Key /c /t /Inheritance:d
          TakeOwn /F $Key
          Write-Output "$env:UserName"
          Icacls $Key /c /t /Grant:r ${env:UserName}:F
          Icacls $Key /c /t /Remove:g Administrator "Authenticated Users" BUILTIN\Administrators BUILTIN Everyone System Users
          Icacls $Key
          Remove-Variable -Name Key
          Get-Service -Name ssh-agent | Set-Service -StartupType Manual
          ssh-agent -s
          ssh-add ../kkk
          ssh -T git@github.com
          git push -f git@github.com:miswanting/Action-Test.git master:gh-pages
      # - name: Setup Python 3 Enviroment
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.9"
      #     architecture: "x64"

      # - name: Custom
      #   shell: bash
      #   run: |
      #     mkdir portable
      #     ls portable
      #     mkdir portable/runtime
      #     ls portable/runtime
      #     cp C:/hostedtoolcache/windows/Python/3.9.*/x64/python.exe portable/runtime
      #     cp C:/hostedtoolcache/windows/Python/3.9.*/x64/python39.dll portable/runtime
      #     cp C:/hostedtoolcache/windows/Python/3.9.*/x64/vcruntime140.dll portable/runtime
      #     cp -r C:/hostedtoolcache/windows/Python/3.9.*/x64/DLLs portable/runtime
      #     cp -r C:/hostedtoolcache/windows/Python/3.9.*/x64/Lib portable/runtime
      #     cp -r C:/hostedtoolcache/windows/Python/3.9.*/x64/Scripts portable/runtime
      #     cd C:/hostedtoolcache/windows/Python/3.9.*/x64
      #     pwd
      #     ls
      #     cd C:/hostedtoolcache/windows/node/14.*/x64
      #     pwd
      #     ls
