name: Release Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      # - name: Get Build Info
      #   id: info
      #   shell: bash
      #   run: |
      #     d=`date +%Y%m%d`
      #     echo ::set-output name=DATE::${d:2:6}
      #     echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}

      - name: Setup Node.js Enviroment
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Build
        run: |
          Get-Location | Write-Output
          Get-ChildItem
          yarn
          yarn run docs:build
      - name: upload
        uses: actions/upload-artifact@v2
        with: 
          name: dist-without-markdown
          path: |
            docs
      # - name: Setup Python 3 Enviroment
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.9"
      #     architecture: "x64"

      # - name: Custom
      #   shell: bash
      #   run: |
      #     mkdir portable
      #     ls portable
      #     mkdir portable/runtime
      #     ls portable/runtime
      #     cp C:/hostedtoolcache/windows/Python/3.9.*/x64/python.exe portable/runtime
      #     cp C:/hostedtoolcache/windows/Python/3.9.*/x64/python39.dll portable/runtime
      #     cp C:/hostedtoolcache/windows/Python/3.9.*/x64/vcruntime140.dll portable/runtime
      #     cp -r C:/hostedtoolcache/windows/Python/3.9.*/x64/DLLs portable/runtime
      #     cp -r C:/hostedtoolcache/windows/Python/3.9.*/x64/Lib portable/runtime
      #     cp -r C:/hostedtoolcache/windows/Python/3.9.*/x64/Scripts portable/runtime
      #     cd C:/hostedtoolcache/windows/Python/3.9.*/x64
      #     pwd
      #     ls
      #     cd C:/hostedtoolcache/windows/node/14.*/x64
      #     pwd
      #     ls
